sudo: required
dist: trusty

language: c

# send build/failure notifications only to a specific
# email address and only on a status change
notifications:
  email:
    recipients:
      - svn@yam.ch
    on_success: change
    on_failure: change

# download and install our required cross compilers
install:
  # Make sure we can install i386 packages as some adtools binaries
  # requires i386 libraries being installed to work in the 64bit env
  # of Travis
  - sudo dpkg --add-architecture i386
  - sudo apt-get -qq update || true
  - sudo apt-get -qq install libc6:i386
  # Install all adtools related stuff we need
  - wget https://dl.bintray.com/jens-maus/adtools/adtools-utils.tar.bz2
  - wget https://dl.bintray.com/jens-maus/adtools/adtools-m68k-amigaos.tar.bz2
  - wget https://dl.bintray.com/jens-maus/adtools/adtools-ppc-amigaos.tar.bz2
  - wget https://dl.bintray.com/jens-maus/adtools/adtools-ppc-morphos.tar.bz2
  - wget https://dl.bintray.com/jens-maus/adtools/adtools-ppc-aros.tar.bz2
  - wget https://dl.bintray.com/jens-maus/adtools/adtools-i386-aros.tar.bz2
  - wget https://dl.bintray.com/jens-maus/adtools/adtools-x86_64-aros.tar.bz2
  - sudo tar xf adtools-utils.tar.bz2 -C /
  - sudo tar xf adtools-m68k-amigaos.tar.bz2 -C /
  - sudo tar xf adtools-ppc-amigaos.tar.bz2 -C /
  - sudo tar xf adtools-ppc-morphos.tar.bz2 -C /
  - sudo tar xf adtools-ppc-aros.tar.bz2 -C /
  - sudo tar xf adtools-i386-aros.tar.bz2 -C /
  - sudo tar xf adtools-x86_64-aros.tar.bz2 -C /

# set the PATH variable to the directories the cross compilers are installed.
before_script:
  - export PATH=/usr/local/amiga/bin:/opt/m68k-amigaos/bin:/opt/ppc-amigaos/bin:/opt/ppc-morphos/bin:${PATH}

# specify a list of variables to test (here we test the build for our supported
# list of operating systems).
env:
  - OS=os4
  - OS=os3
  - OS=mos
  - OS=i386-aros
  - OS=ppc-aros
  - OS=x86_64-aros

# the build command to execute for each test
script:
  - make OS=${OS} -j1
