sudo: required
dist: trusty

language: c

# send build/failure notifications only to a specific
# email address and only on a status change
notifications:
  email:
    recipients:
      - svn@yam.ch
    on_success: change
    on_failure: change

# download and install our required cross compilers
install:
  # Make sure we can install i386 packages as some adtools binaries
  # requires i386 libraries being installed to work in the 64bit env
  # of Travis
  - sudo dpkg --add-architecture i386
  - sudo apt-get -qq update || true
  - sudo apt-get -qq install libc6:i386
  # Install all adtools related stuff we need
  - curl -L https://dl.bintray.com/jens-maus/adtools/adtools-utils.tar.bz2 | sudo tar xj -C /
  - if [[ ${BUILD} =~ os3|release ]]; then curl -L https://dl.bintray.com/jens-maus/adtools/adtools-m68k-amigaos.tar.bz2 | sudo tar xj -C / ; fi
  - if [[ ${BUILD} =~ os4|release ]]; then curl -L https://dl.bintray.com/jens-maus/adtools/adtools-ppc-amigaos.tar.bz2 | sudo tar xj -C / ; fi
  - if [[ ${BUILD} =~ mos|release ]]; then curl -L https://dl.bintray.com/jens-maus/adtools/adtools-ppc-morphos.tar.bz2 | sudo tar xj -C / ; fi
  - if [[ ${BUILD} =~ aros-ppc|release ]]; then curl -L https://dl.bintray.com/jens-maus/adtools/adtools-ppc-aros.tar.bz2 | sudo tar xj -C / ; fi
  - if [[ ${BUILD} =~ aros-i386|release ]]; then curl -L https://dl.bintray.com/jens-maus/adtools/adtools-i386-aros.tar.bz2 | sudo tar xj -C / ; fi
  - if [[ ${BUILD} =~ aros-x86_64|release ]]; then curl -L https://dl.bintray.com/jens-maus/adtools/adtools-x86_64-aros.tar.bz2 | sudo tar xj -C / ; fi

# set the PATH variable to the directories the cross compilers are installed.
before_script:
  - export PATH=/usr/local/amiga/bin:/opt/m68k-amigaos/bin:/opt/ppc-amigaos/bin:/opt/ppc-morphos/bin:${PATH}

# specify a list of variables to test (here we test the build for our supported
# list of operating systems).
env:
  - BUILD="OS=os4"
  - BUILD="OS=os4 DEBUG="
  - BUILD="OS=os3"
  - BUILD="OS=os3 DEBUG="
  - BUILD="OS=mos"
  - BUILD="OS=mos DEBUG="
  - BUILD="OS=aros-ppc"
  - BUILD="OS=aros-ppc DEBUG="
  - BUILD="OS=aros-i386"
  - BUILD="OS=aros-i386 DEBUG="
  - BUILD="OS=aros-x86_64"
  - BUILD="OS=aros-x86_64 DEBUG="
  - BUILD="release" OUTPUT=">/dev/null"

# the build command to execute for each test
script:
  - travis_wait 30 make -j1 ${BUILD} ${OUTPUT}

# deploy snapshots to bintray
deploy:
  provide: bintray
  user: jens-maus
  on:
    branch: master
    condition: ${BUILD} =~ snapshot
  key:
    secure: bvgGEg+zjiMffttyeiYp393H9AaeJ1M/c5WCeXu+f4bZYvzDN1n8EydFrfogYxjV/khIWGtlZMGVItQTJPy7XfKKZhgakhBzpihkXBBKybRkKKyAUzrP+3P4a8A97I+7do+4L7Gj8iH/UNIumc7geiIqY+8cf8z9nOxc8SOZLO4brLlGYCPDjbQalPp74CHQjyCSZU+4r4YzYpqX/S98fAHU3e+EKuBOh8yQhJ20zTND5KKE6C4B+Kop5eoGv1D3d+qbI67YUitPqAPspFAJwOPVxyNR26Sztc6DUem81CW6BhZUKuZ1Jm2goS+nSKFF1Te2WfFWiqtxxdHJdoZNVc9y8yge7o/TUNv6DdF1DyHs0MjxffULrZiCF8l7UPIIhqulM+ZneJ64yoY6nqYgHpaiBjC6mpMPHqwYoy1v9iSa96qel+mlRYfnYy9Jj72ZvgdZNBviQYhRRMOX4LqqsFm+r4h38PPU9ZTAuCKYom2vjQ5zQ+DTvzWjCuWxOlxVPyYRPC0QRb1YOtaIuOPCQG0zpx669MK3H2AMmaTQIn0g2qZWfADf3b5rPywvST5dg4Z2NrPWEAC9xRBtRCn6I5wBep/UTquyeVE0SbP3KII8OejARHUue73ODuUJz8HsTfoJekWVQ5C+6aH5YaUgthnb9KfgFbEw7ptolV8y1DE=
