name: nightly
on:
  schedule:
    - cron: '0 1 * * *' # run at 1 AM UTC

jobs:
  repo-change-check:
    name: repository change check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - id: commit-check
        run: 'echo ::set-output name=has-commits::$(git --no-pager log --pretty=oneline --since="24 hours ago" | wc -l)'
    outputs:
      has-commits: ${{ steps.commit-check.outputs.has-commits }}

  build:
    runs-on: ubuntu-20.04
    needs: repo-check
    timeout-minutes: 480

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: setup dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update -y -qq || true
        sudo apt-get -qq install libc6:i386
        sudo ln -s /usr/lib/x86_64-linux-gnu/libmpfr.so.6 /usr/lib/x86_64-linux-gnu/libmpfr.so.4

    - name: setup env
      run : |
        echo "DATE=$(date +%Y%m%d)" >>$GITHUB_ENV
        echo "GITHUB_SHA7=$(echo ${GITHUB_SHA::7})" >>$GITHUB_ENV
        echo YAMVER=$(grep '#define __YAM_VERSION' src/YAM_global.c | cut -d '"' -f2) >>$GITHUB_ENV

    - name: install adtools build env
      run: |
        curl -L https://dl.bintray.com/jens-maus/adtools/adtools-utils.tar.bz2 | sudo tar xj -C /
        curl -L https://dl.bintray.com/jens-maus/adtools/adtools-m68k-amigaos.tar.bz2 | sudo tar xj -C /
        curl -L https://dl.bintray.com/jens-maus/adtools/adtools-ppc-amigaos.tar.bz2 | sudo tar xj -C /
        curl -L https://dl.bintray.com/jens-maus/adtools/adtools-ppc-morphos.tar.bz2 | sudo tar xj -C /
        curl -L https://dl.bintray.com/jens-maus/adtools/adtools-ppc-aros.tar.bz2 | sudo tar xj -C /
        curl -L https://dl.bintray.com/jens-maus/adtools/adtools-i386-aros.tar.bz2 | sudo tar xj -C /
        curl -L https://dl.bintray.com/jens-maus/adtools/adtools-x86_64-aros.tar.bz2 | sudo tar xj -C /

    - name: cleanup old action artifacts
      run: .github/workflows/purge_artifacts.sh ${{ secrets.GITHUB_TOKEN }}

    #- name: remote debug tmate session
    #  uses: mxschmitt/action-tmate@v1
    #  if: matrix.platform == 'os4'

    - name: build YAM nightlies
      timeout-minutes: 480
      run: |
        export PATH=/usr/local/amiga/bin:/opt/m68k-amigaos/bin:/opt/ppc-amigaos/bin:/opt/ppc-morphos/bin:${PATH}
        make -j1 nightly

    - name: upload AmigaOS4 files as workflow artifact [release]
      uses: actions/upload-artifact@v2
      with:
        path: YAM${{ env.YAMVER }}dev-${{ env.DATE }}-AmigaOS4.lha*
        name: YAM${{ env.YAMVER }}dev-${{ env.DATE }}-AmigaOS4.lha
      continue-on-error: true

    - name: upload AmigaOS4 files as workflow artifact [debug]
      uses: actions/upload-artifact@v2
      with:
        path: YAM${{ env.YAMVER }}dev-${{ env.DATE }}-AmigaOS4-debug.lha*
        name: YAM${{ env.YAMVER }}dev-${{ env.DATE }}-AmigaOS4-debug.lha
      continue-on-error: true

    - name: upload AmigaOS3 files as workflow artifact [release]
      uses: actions/upload-artifact@v2
      with:
        path: YAM${{ env.YAMVER }}dev-${{ env.DATE }}-AmigaOS3.lha*
        name: YAM${{ env.YAMVER }}dev-${{ env.DATE }}-AmigaOS3.lha
      continue-on-error: true

    - name: upload AmigaOS3 files as workflow artifact [debug]
      uses: actions/upload-artifact@v2
      with:
        path: YAM${{ env.YAMVER }}dev-${{ env.DATE }}-AmigaOS3-debug.lha*
        name: YAM${{ env.YAMVER }}dev-${{ env.DATE }}-AmigaOS3-debug.lha
      continue-on-error: true

    - name: upload MorphOS files as workflow artifact [release]
      uses: actions/upload-artifact@v2
      with:
        path: YAM${{ env.YAMVER }}dev-${{ env.DATE }}-MorphOS.lha*
        name: YAM${{ env.YAMVER }}dev-${{ env.DATE }}-MorphOS.lha
      continue-on-error: true

    - name: upload MorphOS files as workflow artifact [debug]
      uses: actions/upload-artifact@v2
      with:
        path: YAM${{ env.YAMVER }}dev-${{ env.DATE }}-MorphOS-debug.lha*
        name: YAM${{ env.YAMVER }}dev-${{ env.DATE }}-MorphOS-debug.lha
      continue-on-error: true
